# The powershell script to run migrations on a specific db context.
# Example usage
# Create autogenerated migration on Curio Client Db Context
# .\Update-Database-EFC.ps1 --projectPath '..\..\src\Curio.Persistence' --startupProjectPath '..\..\src\Curio.Persistence.Tools' --contextName 'CurioClientDbContext'
param
(
    [Alias('p')]
    [Parameter(Mandatory)]
    $projectPath,

    [Alias('sp')]
    [Parameter(Mandatory)]
    $startupProjectPath,

    [Alias('c')]
    [Parameter(Mandatory)]
    $contextName,

    $migrationName
)

if ($migrationName -eq $null) {
    $today = Get-Date -Format "yyyyMMddHHmmss"
    $migrationName = "${today}AutoNamedMigration";
}

Write-Host "Updating the database via dotnet CLI for Entity Framework Core" -ForegroundColor Green -BackgroundColor Gray
Write-Host ""

Write-Host "Updating entity framework tools to the latest version globally if not up-to-date" -ForegroundColor Yellow
dotnet tool update --global dotnet-ef

Write-Host "==============================================" -ForegroundColor Gray

$projectPath = Resolve-Path '..\..\src\Curio.Persistence'
Write-Host "Project Path: " -ForegroundColor Blue -NoNewline
Write-Host ${projectPath} -ForegroundColor Green -NoNewline
$projectPathExits = Test-Path "${projectPath}"
Write-Host " [Exists] = ${projectPathExits}" -ForegroundColor Blue

$startupProjectPath = Resolve-Path '..\..\src\Curio.Persistence.Tools'
Write-Host "Startup Project Path: " -ForegroundColor Blue -NoNewline
Write-Host ${startupProjectPath} -ForegroundColor Green -NoNewline
$startupProjectPathExits = Test-Path "${projectPath}"
Write-Host " [Exists] = ${startupProjectPathExits}" -ForegroundColor Blue

$contextName = "CurioClientDbContext"
Write-Host "DbContext: " -ForegroundColor Blue -NoNewline
Write-Host "${contextName}" -ForegroundColor Blue -BackgroundColor White
Write-Host "==============================================" -ForegroundColor Gray

dotnet ef migrations add $migrationName --project $projectPath --startup-project $startupProjectPath --context $contextName