name: .NET 5 CI (Build + Test runner)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Curio .NET 5 build
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.200 #look for SDK Version https://dotnet.microsoft.com/download/dotnet/
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build with dotnet (Release)
      run: dotnet build --configuration Release
    - name: Test with dotnet (Release)
      run: dotnet test ./Curio.sln --configuration Release
